baseURL      = "https://pontaro.top/"
languageCode = "en-us"
title        = "pontaro"
theme        = "hugo-theme-stack"

defaultContentLanguage = "en"
hasCJKLanguage         = true

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
