[[main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    [main.params]
        icon = "home"
        newTab = false

[[main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog/"
    [main.params]
        icon = "archives"
        newTab = false
