[[main]]
    identifier = "home"
    name       = "Pon"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"
        newTab = false

[[main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog/"
    weight     = 2
    [main.params]
        icon = "archives"
        newTab = false
