[[main]]
    identifier = "home"
    name       = "Pon"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"
        newTab = false

[[main]]
    identifier = "post"
    name       = "Posts"
    url        = "/post/"
    weight     = 2
    [main.params]
        icon = "archives"
        newTab = false
