mainSections = ["blog"]
rssFullContent = true

[footer]
# No 'since' - shows just current year

[dateFormat]
published = ":date_full"
lastUpdated = ":date_full"

[sidebar]
emoji = ""
subtitle = "my thoughts and my favorite things"

[article]
headingAnchor = false
math = false
toc = true
readingTime = true
[article.license]
enabled = false

[widgets]
homepage = [{ type = "categories", params = { limit = 10 } }]
page = [{ type = "toc" }]

[colorScheme]
toggle = false
default = "light"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

[comments]
enabled = false
